### ISSUE TITLE
Portal module doesn't response at GET request in case of SingleWAR and UberJAR deployment

### ISSUE THREAD

**Issue by myatlevEvg** [cuba-platform/jpawebapi#8]
1) Create an application with Platform version 7.1+
2) Add  jpawebapi addon
3) Add Portal module
4) Build SingleWar
5) Start app server
6) Try to send GET to the portal via ```http://localhost:8080/app-portal/api/login?u=admin&p=admin&l=ru```

AR: No response from portal module
![image](https://user-images.githubusercontent.com/33958996/60092228-8f155680-9757-11e9-8c27-794e1ed9b94a.png)

Try the same steps for UberJAR deployment.
AR: 
![image](https://user-images.githubusercontent.com/33958996/60093469-8b370380-975a-11e9-8c8e-87cf639bc047.png)

**Comment by NikitaShchienko** [comment]
Hello,

The portal module does not work in SingleWar. (https://doc.cuba-platform.com/manual-7.0/build.gradle_buildWar.html)
> Single WAR contains only core and web modules (Middleware and Web Client). To deploy the portal module, use separate WAR files.

And in UberJar to access the portal module, you need to send a request to port 8081. 
**Example:**
Portal: http://localhost:8081/app-portal/api/login?u=admin&p=admin&l=ru
Web: http://localhost:8080/app/dispatch/api/login?u=admin&p=admin&l=ru


Since in UberJar each module works on its own port. (https://doc.cuba-platform.com/manual-7.0/build.gradle_buildUberJar.html)

> webPort - port for single (if singleJar=true) or web JAR embedded HTTP server, 8080 if not defined. Can also be set at run time using the -port command line argument.
> 
> corePort - port for core JAR embedded HTTP server, 8079 if not defined. Can also be set at run time using the -port command line argument for the respective JAR.
> 
> portalPort - port for portal JAR embedded HTTP server, 8081 if not defined. Can also be set at run time using the -port command line argument for the respective JAR.
